apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: ap-southeast-1

vpc:
  id: vpc-016882371e9921893
  cidr: "192.168.0.0/16"
  subnets:
    public:
      ap-southeast-1a:
        id: subnet-0ddfdc1499f910eec
      ap-southeast-1b:
        id: subnet-093f97590e6d2faa6
    private:
      ap-southeast-1a:
        id: subnet-08a7f0f746c61bae4
      ap-southeast-1b:
        id: subnet-0d82293c66ca34215

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true
